### ISSUE TITLE
How this repository is supposed to handle binaries?

### ISSUE THREAD

**Issue by glasswalk3r** [cpan-testers/cpantesters-web#8]
I tried to use `DBD::Mock` to generate testing for the unit tests, but `DBIx::Connection` does not support it.
I also tried to use binary files (due how the reports are stored on Mysql) but the result is the same of using a SQLite3 database files.
Then I tried loading data to SQLite3 databases files, dumping the tables with `.dump`, but generated data is incompatible.
I ended up creating a script that queries the Mysql DB and generates very small SQLite DB files:

```
$ ls -l t/data
total 68
-rw-r--r-- 1 alceu alceu 12288 Mai 19 22:11 cpanstats
-rw-r--r-- 1 alceu alceu 32768 Mai 19 22:11 metabase
-rw-r--r-- 1 alceu alceu 24576 Mai 19 22:11 testers
```

But they are binary anyway. One options is to use a [gitattributes](https://www.git-scm.com/docs/gitattributes) file and set them as binaries, so Github will not to try to track them. They shouldn't change over time unless the DB schema (or data) changes substantially. And can be generated again with `create_mock` script.

The DB files have only the absolutely necessary data do execute the unit tests scripts.

**Comment by preaction** [comment]
I don't understand what's happening here. There will be plenty of "binaries" in this repository: Images and fonts needed by the website. I have never needed to use the gitattributes file to put binaries in a git repository. You could give them an extension of `.db` to help Github out, though.

Nobody will be able to run that script that queries the MySQL database because the MySQL database is not available to the outside world. It will especially not be able to be built by the Travis CI, since I will never be able to allow all of Travis's IPs to access the database.

You can create the data you need for testing using code, like I did in the API: https://github.com/cpan-testers/cpantesters-api/blob/b980b538bce76b01adf2e4f725a9f974b0cc4cc5/t/legacy/metabase.t and https://github.com/cpan-testers/cpantesters-api/blob/b980b538bce76b01adf2e4f725a9f974b0cc4cc5/bin/cpantesters-legacy-metabase

**Comment by glasswalk3r** [comment]
> I don't understand what's happening here. There will be plenty of "binaries" in this repository: Images and fonts needed by the website. 

I asked for information about how this project handle binaries over Git.

> I have never needed to use the gitattributes file to put binaries in a git repository.

It is not a requirement, but useful. Git will just skip comparing the files marked as binaries.

> Nobody will be able to run that script that queries the MySQL database because the MySQL database is not available to the outside world. It will especially not be able to be built by the Travis CI, since I will never be able to allow all of Travis's IPs to access the database.

Another reason for trying to make the tests independent regarding fixtures. I can keep the script to generate the data by querying the DB, but storing the data as CSV files.

> You can create the data you need for testing using code, like I did in the API

I'm using DBIx::Connection (see [this](http://search.cpan.org/~dwheeler/DBIx-Connector-0.56/lib/DBIx/Connector.pm#Description) for the benefits of it), it doesn't support DBD::Mock but since it does supports SQLite, I think it is doable. I would only need to save the report itself as JSON under the `data` folder and import it back into the "memory DB" and would be (hopefully) compatible with Data::FlexSerializer when trying to get it back. Since JSON is not binary itself, the binary files usage will be avoided.

That will hold back the  #9 request until I complete those changes, so you will probably want to reject the request for now.

**Comment by preaction** [comment]
I've never seen Git try to diff a binary file. It's always just seemed to know not to. I don't know if that works because I'm on a platform that has a `file(1)` command or if it's just something git just magically knows.

For tracking binary files in git repos: If it's a binary file that is generated from other data, I'd prefer not to track it through git (as is standard for those kinds of things). For large binary files (greater than a few megabytes) that are not generated, I'd prefer to not keep them in the git repository if we can at all avoid it (I've tried using git-lfs on Github to no good effect, and I might need to set something up on the cpantesters.org server for that to work right). For any other binary file scenario, I'd have to know specifics and rationales to be able to discuss how they should be handled.

If you want to store the test data as JSON or what-have-you inside the distribution, I've been using the `t/share` directory in other distributions. It's like the `share` directory, but only for test data so it's not installed. Then I use FindBin to find the `t/share` directory (it looks like you've used that module before). I often use Mojo::File or Path::Tiny (effectively the same module, but don't let the authors know I said that) to make reading the files in `t/share` easier (because File::Spec and File::Spec::Functions are cumbersome, and File::Slurp isn't recommended anymore).

I've never used DBIx::Connector, but the documentation you linked to and [this StackOverflow thread](https://stackoverflow.com/questions/8353359/what-are-the-advantages-of-using-dbixconnector-over-simply-setting-mysql-auto) make it seem like it's a basic reconnecter with some better APIs. So, that's fine. I use `mysql_auto_reconnect` in other places in the codebase.
